#!/usr/bin/env ruby
#^syntax detection

site "https://galaxy.ansible.com/api/v1"

role "ansible-docker",
  github: "mhamrah/ansible-docker"
role "ansible-java8",
  github: "mhamrah/ansible-java8"
role "ansible-zookeeper",
  github: "AnsibleShipyard/ansible-zookeeper"
role "ansible-marathon",
  github: "AnsibleShipyard/ansible-zookeeper"
role "ansible-mesos",
  github: "AnsibleShipyard/ansible-zookeeper"
role "ansible-consul",
  github: "savagegus/ansible-consul"
role "franklinkim.nginx",
  github: "weareinteractive/ansible-nginx"
role "geerlingguy.nginx",
  github: "geerlingguy/ansible-role-nginx"
role "joshualund.golang",
  github: "jlund/ansible-go"